### ISSUE TITLE
Коммент по ДЗ.

### ISSUE THREAD

**Issue by sapolio** [Viktor85-prog/HLS-player#1]
Привет.
Работает хорошо.
Лайв в VOD конвертировать не нужно. Тот, что есть, подходит. Или можно такой https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8

К собеседованию, если будет воля, предлагаем доработки на выбор:
- Немного очеловечить вывод длинных дробных частей, чтобы не мелькали и проще читались
- отключить у плеера нативные контроли и написать свои. В количестве и глубине пропработки, какие сочтёте уместными.

Сложность:
"Изи" — кнопка плей-пауза.
"Подключаем вторую руку" — кнопка фулскрин с сохранением интерфейса поверх плеера.
"Помучиться" — отзывчивый ползунок перемотки.

**Comment by Viktor85-prog** [comment]
все предложения реализовал, добавил стилей
